<Project>
  <PropertyGroup>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <TestTfm>net10.0</TestTfm>
    <SerdeAssemblyVersion>0.10.1-alpha.9</SerdeAssemblyVersion>
    <SerdePkgVersion>0.10.1-alpha.9</SerdePkgVersion>
  </PropertyGroup>
</Project>
